name: printpro_manager
description: A beautiful print management dashboard UI
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  curved_navigation_bar: ^1.0.6
  shimmer: ^3.0.0
  http: ^1.6.0
  record: ^6.1.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  audioplayers: ^6.5.1
  speech_to_text: ^7.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
